config:
  azure-native:location: uksouth
  cloudflare:apiToken:
    secure: AAABAK5x3wDS5C76tQnq1VeJY+X7kKr57staLWCYI2KxGU6uuW7v/XPUflo74gzPrjxBUiZe52ClMMUsUVW8xm3EzxSeAiE0
  now-u:authServiceJwtSecret:
    secure: AAABAPX9y7RE8Ff2Xaf42R/X3iaE6d70pnxa2At0Y3j35++xtrJrUh6bZLxXqH+eS07QLHTa2nEmy5kz0q/7eC9dDdzsA56SJew9AhyfzVH99UpN9BMkavX8p59ptO85vMnUjOz5F4WP5o1PITZ9AmAvP98i3kTx
  now-u:cloudflareZoneId:
    secure: AAABAJMUDNqpI2s1HRpHiKVEEN8bCJw7S2BzZy+tTb3lF1kN2brZdOe11I3cqjIjfmuISD2DIpBzoi6Z5xChjA==
  now-u:containerPort: "5000"
  now-u:cpu: "1"
  now-u:customDomainVerificationId:
    secure: AAABAPHZxJR/TiOaMdStpeu98t0SppOrIk0MH8jvTozHUTUaM+iATg+t+jCj9rn5+rRiWQUV69hYRsQhGJeTmQTRP7HxETZj8OhgdJM8OU38VjcUTa7+UoI7T8e5T+nh
  now-u:djangoAdminEmail:
    secure: AAABAG6JwsR/gkXbyvGE37sBnhUkzp4duzMq2OdPsb6cKtzMcfB4EF7nVXZ7sd/k0+BbeZlZHLvIWRSGlvU=
  now-u:djangoAdminPassword:
    secure: AAABAMDTkUcWtaKZLUzz+kZOUWXwxrAwOYQSY5q4qj8jofT9T5UCsKDAuniY5PFUc/+kfq4ZttH4D464iSuNZQ==
  now-u:memory: "2"
