"""
Django settings for now_u_api project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import os

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

BASE_URL = os.getenv('BASE_URL', 'http://192.168.1.11:8000')

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=2ni(vbte78nlvoip2+*pydk8(+z4ewov&8ns9+$6%5*b%dqhe'

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    f'https://{BASE_URL}',
]


# Application definition

INSTALLED_APPS = [
    'causes.apps.CausesConfig',
    'users.apps.UsersConfig',
    'images.apps.ImagesConfig',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'drf_spectacular',
    'django_saml2_auth',

    # Admin
    'admin_interface',
    'colorfield',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'now_u_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'now_u_api.wsgi.application'

STATIC_FILES_STORAGE_CONTAINER = os.getenv("STATIC_FILES_STORAGE_CONTAINER", None)

if STATIC_FILES_STORAGE_CONTAINER is not None:
    STATIC_FILES_STORAGE_ACCOUNT_NAME = os.getenv("STATIC_FILES_STORAGE_ACCOUNT_NAME")
    STATIC_FILES_STORAGE_ACCOUNT_KEY = os.getenv("STATIC_FILES_STORAGE_ACCOUNT_KEY")

    STORAGES = {
        "default": {"BACKEND": "storages.backends.azure_storage.AzureStorage"},
        "staticfiles": {"BACKEND": "now_u_api.storage.PublicAzureStorage"},
    }

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
    }
}


AUTH_USER_MODEL = 'users.User'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # TODO Add base authentication class which lets you authenticate if you are logged into admin
        'now_u_api.authentication.NowuTokenAuthentication',
    ]
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'now-u cause API',
    'DESCRIPTION': 'now-u service to fetch causes data',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
}

SAML2_AUTH = {
    'DEBUG': True,
    # Metadata is required, choose either remote url or local file path
    'METADATA_LOCAL_FILE_PATH': os.path.join(BASE_DIR,'GoogleIDPMetadata.xml'),

    # Optional settings below
    'DEFAULT_NEXT_URL': '/admin',  # Custom target redirect URL after the user get logged in. Default to /admin if not set. This setting will be overwritten if you have parameter ?next= specificed in the login URL.
    'CREATE_USER': 'TRUE', # Create a new Django user when a new user logs in. Defaults to True.
    'NEW_USER_PROFILE': {
        'USER_GROUPS': [],  # The default group name when a new user logs in
        'ACTIVE_STATUS': True,  # The default active status for new users
        'STAFF_STATUS': True,  # The staff status for new users
        'SUPERUSER_STATUS': False,  # The superuser status for new users
    },
    'ATTRIBUTES_MAP': {  # Change Email/UserName/FirstName/LastName to corresponding SAML2 userprofile attributes.
        'email': 'Email',
        'first_name': 'FirstName',
        'last_name': 'LastName',
        'groups': 'Groups',
    },
    # TODO Setup seeds for these groups with correct perms
    # TODO If not already done, before login, if user exists update their group memberships
    'GROUPS_MAP': {
        'campaigns': 'Campaigns',
        'dev': 'Development',
    },
    # 'AUTHN_REQUESTS_SIGNED': False,
    # 'WANT_ASSERTIONS_SIGNED': True,
    'WANT_RESPONSE_SIGNED': False,
    'TRIGGER': {
        # 'CREATE_USER': 'path.to.your.new.user.hook.method',
    #     # 'BEFORE_LOGIN': 'path.to.your.login.hook.method',
    },
    'ASSERTION_URL': BASE_URL, # Custom URL to validate incoming SAML requests against
    'ENTITY_ID': f'{BASE_URL}/saml2_auth/acs/', # Populates the Issuer element in authn request
    # 'NAME_ID_FORMAT': FormatString, # Sets the Format property of authn NameIDPolicy element
    'USE_JWT': False, # Set this to True if you are running a Single Page Application (SPA) with Django Rest Framework (DRF), and are using JWT authentication to authorize client users
    # 'FRONTEND_URL': 'https://myfrontendclient.com', # Redirect URL for the client if you are using JWT auth with DRF. See explanation below
    'TOKEN_REQUIRED': False,
}

# TODO Assert not none and secret if is
JWT_SECRET = os.getenv('JWT_SECRET')

MAILCHIMP = {
    'API_KEY': os.getenv('MAILCHIMP_API_KEY'),
    'LIST_ID': os.getenv('MAILCHIMP_LIST_ID'),
    'SERVER': os.getenv('MAILCHIMP_SERVER'),
}
