# Generated by Django 4.2.2 on 2023-08-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0017_alter_usercause_user'),
        ('users', '0002_alter_user_auth_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_causes',
            field=models.ManyToManyField(through='causes.UserCause', to='causes.cause'),
        ),
    ]
