# Generated by Django 5.1 on 2024-09-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_image_alt_text_alter_image_internal_name'),
        ('users', '0006_remove_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_profile_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blog_profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
    ]
