# Generated by Django 4.2.2 on 2023-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='internal_name',
            field=models.CharField(blank=True, help_text='A name used to identity the image internally in the admin panel', max_length=100, null=True),
        ),
    ]
