# Generated by Django 4.2.2 on 2023-07-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0003_alter_action_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
