# Generated by Django 4.2.2 on 2023-07-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_alter_action_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
