# Generated by Django 4.2.2 on 2023-07-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0005_alter_action_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='link',
            field=models.URLField(max_length=3000),
        ),
    ]
