# Generated by Django 4.2.2 on 2023-07-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0007_alter_learningresource_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
