# Generated by Django 4.2.2 on 2023-07-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0008_alter_learningresource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='source',
            field=models.CharField(max_length=300),
        ),
    ]
