# Generated by Django 4.2.2 on 2023-07-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0009_alter_learningresource_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
