# Generated by Django 4.2.2 on 2023-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0011_alter_newsarticle_source_alter_newsarticle_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
