# Generated by Django 4.2.2 on 2023-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0012_alter_newsarticle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.URLField(max_length=300),
        ),
    ]
