# Generated by Django 4.2.2 on 2023-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0013_alter_newsarticle_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
