# Generated by Django 4.2.2 on 2023-07-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_image'),
        ('causes', '0014_alter_newsarticle_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='causes', to='causes.cause'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('actions', models.ManyToManyField(blank=True, related_name='themes', to='causes.action')),
                ('campaigns', models.ManyToManyField(blank=True, related_name='themes', to='causes.campaign')),
                ('header_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('learning_resources', models.ManyToManyField(blank=True, related_name='themes', to='causes.learningresource')),
            ],
        ),
    ]
