# Generated by Django 4.2.2 on 2023-08-27 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('causes', '0016_alter_cause_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercause',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
