# Generated by Django 4.2.2 on 2023-09-11 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0017_alter_usercause_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='learningresource',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='action',
            name='release_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date from which this resource should be available in the app. If not provided the resource will not be visible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='release_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date from which this resource should be available in the app. If not provided the resource will not be visible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='release_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date from which this resource should be available in the app. If not provided the resource will not be visible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='release_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date from which this resource should be available in the app. If not provided the resource will not be visible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='release_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date from which this resource should be available in the app. If not provided the resource will not be visible'),
            preserve_default=False,
        ),
    ]
