# Generated by Django 4.2.2 on 2023-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0018_remove_action_enabled_remove_campaign_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='learning_resources',
        ),
        migrations.AddField(
            model_name='cause',
            name='news_articles',
            field=models.ManyToManyField(blank=True, related_name='new_articles', to='causes.newsarticle'),
        ),
    ]
