# Generated by Django 4.2.2 on 2023-11-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0020_alter_theme_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
