# Generated by Django 4.2.2 on 2023-12-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0021_alter_theme_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='causes.action'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='learning_resources',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='causes.learningresource'),
        ),
    ]
