# Generated by Django 4.2.2 on 2023-12-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0023_newsarticle_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='news_articles',
            field=models.ManyToManyField(blank=True, related_name='causes', to='causes.newsarticle'),
        ),
    ]
