# Generated by Django 5.1 on 2024-10-25 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0026_alter_useraction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearningresources',
            name='learning_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='causes.learningresource'),
        ),
    ]
