# Generated by Django 5.1 on 2025-01-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0027_alter_userlearningresources_learning_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='long_description',
            field=models.TextField(default='TODO'),
            preserve_default=False,
        ),
    ]
