# Generated by Django 5.1 on 2025-03-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0028_cause_long_description'),
        ('images', '0005_alter_image_alt_text_alter_image_internal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='secondary_image',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='cause_secondary_images', to='images.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cause',
            name='header_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_header_images', to='images.image'),
        ),
    ]
