on:
  workflow_call:

jobs:
  causes-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: now-u/now-u-causes

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:causes_service"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
