on:
  workflow_call:

jobs:
  deploy-base-infra:
    runs-on: ubuntu-latest
    env:
      # TODO I think the issue is this access token is not for org. Verify and
      # swap out backend to use azure blob.
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      PULUMI_CREDENTIALS_PATH: /github/home/.pulumi
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Setup pulumi
        uses: pulumi/actions@v4
        with:
          work-dir: infra
          stack-name: now-u/now-u-infra

      - name: Test 2 pulumi
        run: echo $PULUMI_ACCESS_TOKEN 

      - name: Test pulumi
        run: sudo pulumi -v=3 org

      - name: Test org
        run: sudo pulumi org

      - name: Install dependencies
        working-directory: infra
        run: npm install

      - name: Deploy base infra
        working-directory: infra
        run: sudo npm run deploy --base-infra
