on:
  workflow_call:

jobs:
  deploy-base-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Deploy base infra
        working-directory: ./infra
        run: npm run deploy --base-infra
